### PR TITLE
Address issue #80

### PR DESCRIPTION
**Pull request by 21stcaveman**
This is to address issues detailed in #80 (except 1 and 7).

### CODE REVIEW

**Comment by RJVB** [comment]
Wow, I hadn't had time to look at issue #80 yet, I wasn't expecting it to be so all-encompassing! It will take me some time to verify and incorporate your changes!

Why was the samba4 upgrade necessary? I know I had a reason not to ship a newer version when I start working on the port, but that's over a year ago. Probably newer versions failed to build, judging from the comment in the Portfile.

As a general remark: most of the custom versions of mainstream ports in my tree have little tweaks or additions that are probably of less interest to others than to myself, and they tend to lag because I can't spend my time updating ports instead of using them.
IOW, for ports like rsync and mesa you can simply install the one from the mainstream tree. A priori this can happen automatically if you install the default variant to the default prefix. If you want to force it (and get the current version), you can invoke the `port` command from inside the mainstream portdir :

```
> sudo port -n install [--subport foo] [+variants]
```

not the absent port name!

**Comment by 21stcaveman** [comment]
Hi there,

I completely understand your time is limited, and I appreciate you spending any time at all on these ports, making it possible for people like me to use what we like from KDE, on Mac. That is exactly why I tried to fix as much as I can, myself. Please feel free to keep what is useful, and drop the rest by rejecting this pull request. I am still very new to macports system, so you'll probably find some mistakes I have made throughout my edits.

Both rsync and mesa actually failed to install even from default for me. So I had to figure out why and put in some fixes for them.

Regarding Samba, neither version of samba was building successfully for me (from your port or default). default has been broken for a while, and your port failed to build for me giving many compile errors on 10.15. I am sure you had your reasons for keeping the version back, but as of today, I have successfully built samba4 v4.13.0, and am using it with Dolphin (devel), Konsole and Kate now on my Mac. No issues with the new version that I can see. If you see that fit, maybe you can bump up the version to 4.13

**Comment by RJVB** [comment]
Hi,

My usual approach is to incorporate changes more or less manually, port by port, and check the build on my own system. That takes time and a lack of social distraction (conditions that will probably be met only in a week) ;)

Sadly I have no way to tell whether you are alone in running into issues on 10.15, but issues with the default (mainstream) version of my ports should be reported on trac.macports.org . If you do, can you either send me a link or put me on the CC list so I can follow things?

**Comment by 21stcaveman** [comment]
Understood, will do.

**Comment by RJVB** [comment]
I'd planned to start processing this today, but it looks like that ship has sailed ... :-/

**Comment by 21stcaveman** [comment]
:)) there's always tomorrow. My day has just started, and I'm probably gonna spend some time on kf5-gwenview... fails in config stage, with "The following REQUIRED packages have not been found: Exiv2..."
I already have exiv2 and kf5-libexiv2 ports installed.

**Comment by 21stcaveman** [comment]
fyi, I have opened #8977 in for samba 4.13.0 in default.

**Review by RJVB — COMMENTED** [review]
Exactly how does modifying the meson.build file affect the build through autoconf? Because that's how the port is (still) intended to build... (I admit I cannot remember why I didn't complete the migration to meson).

**Comment by 21stcaveman** [comment]
so, the error that I got was :
u_queue.c:174:7: error: implicit declaration of function 'timespec_get' is invalid in C99

the way I fixed it myself, was by changing the standard in src/utils/Makefile to c11 instead of c99.
then, I noticed this has been implemented using the meson.build file in the [main mesa project](https://gitlab.freedesktop.org/yurikoles/mesa/-/commit/f7ee5b9b636cf8b7d1776b17824ada5c77a64c83)
hence, the patch I submitted (just noticed that patch has a typo, = is missing!).

**Review by RJVB — COMMENTED** [review]
Shouldn't this be only for the `+bdjava` variant? FWIW I think the port built for me because I must have the OpenJRE/JDK 7 installed (see the variant description).

**Comment by 21stcaveman** [comment]
> Shouldn't this be only for the `+bdjava` variant? FWIW I think the port built for me because I must have the OpenJRE/JDK 7 installed (see the variant description).

Gotta be honest here, I still don't understand the macports variants completely, so I can't really say. I did not specify any variants when trying to install, and this was part of kf5-dolphin dependencies that failed.
If you think it should only be applied to one variant, please do so.

**Comment by RJVB** [comment]
On Thursday October 29 2020 11:18:55 Hamid Maadani wrote:

>Gotta be honest here, I still don't understand the macports variants completely, so I can't really say. I did not specify any variants when trying to install, and this was part of kf5-dolphin dependencies that failed.

If it failed for you without specifying any variants then I must have overlooked a dependency. Annoying, because I thought I tested this... (IIRC it was the reason of having a variant)

Can you remember the name of the missing command?

**Comment by RJVB** [comment]
>changing the standard in src/utils/Makefile to c11 instead of c99.

^^^^ 

Aha!

And I noticed the samba4 dependency on yapp too. AND ran into compile errors. Both in the idl files (will have to see if those are fatal), and with AT_REMOVEDIR and family macros. Looking into that.

**Review by RJVB — COMMENTED** [review]
Remind me why you updated the samba4 port? After adding the LegacySupport PG it now builds for me. I figured out how to re-activate SMB1 support; I'll need to dust off a Win10 computer for further testing tomorrow.

There will be some changes that I think you'll want to apply to your official submission too so keep an eye out on my repo. (As usual the changes from here will be added via step-by-step commits.)

**Comment by 21stcaveman** [comment]
> Remind me why you updated the samba4 port? After adding the LegacySupport PG it now builds for me. I figured out how to re-activate SMB1 support; I'll need to dust off a Win10 computer for further testing tomorrow.
> 
> There will be some changes that I think you'll want to apply to your official submission too so keep an eye out on my repo. (As usual the changes from here will be added via step-by-step commits.)

samba4 was another dependency of dolphin (or a dependency of a dependency, not sure), and it kept failing to build. I tried multiple things to fix the version you had (can't remember what exactly), and it would just fail. I tried to install the one from default, and noticed default has been broken for forever. So I thought I would give the latest version a shot.
After disabling docs, and fixing a mac compatibility issue, it built and installed just fine.

Absolutely, I'll keep an eye out for your changes.

**Comment by RJVB** [comment]
>samba4 was another dependency of dolphin (or a dependency of a dependency, not sure)

Of kio-extras.

>, and it kept failing to build.

OK, so the older version fails on newer OS versions... aaargh!

>After disabling docs, and fixing a mac compatibility issue, it built and installed just fine.

Docs had to be disabled in 4.8.9 too, not sure why, but who reads them anyway... beyond the manpages that still get installed

**Comment by 21stcaveman** [comment]
Rene, what'd be a good email to use to copy you on trac tickets?

**Pull request closed without merging**
